### ISSUE TITLE
better performance

### ISSUE THREAD

**Issue by zhaishengfu** [CaptainProton42/2DGrassShaderDemo#3]
I find that there are for loop, and in some situations, we can add break to make better performance. at least for your situation, add break does not affect the result
![image](https://user-images.githubusercontent.com/7630101/97824460-f69dc780-1cf6-11eb-9940-94c3cc65afad.png)
I think only in few situations this will cause influence

**Comment by CaptainProton42** [comment]
You're right, good spot!
